# Generated by Django 4.2.10 on 2024-02-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0, max_length=5)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='images/books/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_books', to='department.department')),
            ],
        ),
    ]
