# Generated by Django 3.2.22 on 2024-02-27 23:53

import book.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='', max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='images/books/')),
                ('popularity', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('number_copies', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), book.models.max_value_current_year])),
                ('isbn_issn', models.IntegerField()),
                ('ddc_number', models.CharField(max_length=50)),
                ('edition_statement', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=80)),
                ('imprint', models.CharField(max_length=50)),
                ('physical_description', models.CharField(max_length=255)),
                ('control_number', models.CharField(max_length=50)),
                ('call_number', models.CharField(max_length=50)),
                ('general_information', models.TextField(default='')),
                ('discipline', models.CharField(blank=True, max_length=80, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_books', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('acronym', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop-pictures/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_photos', to='book.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='book.Tags'),
        ),
    ]
