# Generated by Django 4.2.10 on 2024-02-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BookPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop-pictures/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_photos', to='book.book')),
            ],
        ),
    ]
