# Generated by Django 3.2.22 on 2024-02-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_popularity_bookphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='iso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
