# Generated by Django 3.2.22 on 2024-02-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_ddc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_issn',
            field=models.CharField(max_length=50, verbose_name='ISBN/ISSN'),
        ),
    ]
