# Generated by Django 3.2.22 on 2024-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_copies',
            field=models.IntegerField(default=0),
        ),
    ]
