# Generated by Django 3.2.22 on 2024-02-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_number_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
