# Generated by Django 3.2.22 on 2024-02-25 00:02

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1984), book.models.max_value_current_year]),
        ),
    ]
