# Generated by Django 3.2.22 on 2024-03-06 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrate',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
