# Generated by Django 3.2.22 on 2024-02-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_photo',
            new_name='cover_photo',
        ),
    ]
