# Generated by Django 3.2.22 on 2024-02-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_book_photo_book_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
