# Generated by Django 3.2.22 on 2024-03-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_bookviewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='view_count',
        ),
    ]
