# Generated by Django 3.2.22 on 2024-03-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_book_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksaved',
            name='is_save',
        ),
    ]
