# Generated by Django 3.2.22 on 2024-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_booksaved_is_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='predicted_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
