# Generated by Django 3.2.22 on 2024-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_predicted_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], default='FIRST', max_length=15),
        ),
        migrations.AddField(
            model_name='book',
            name='year_level',
            field=models.CharField(choices=[('FIRST', 'First Year'), ('SECOND', 'Second Year'), ('THIRD', 'Third Year'), ('FOURTH', 'Fourth Year')], default='FIRST', max_length=15),
        ),
    ]
