# Generated by Django 3.2.22 on 2024-03-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20240323_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book Management', 'verbose_name_plural': 'Book Management'},
        ),
        migrations.AlterModelOptions(
            name='bookrate',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='booksaved',
            options={'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='bookviewcount',
            options={'verbose_name': 'View Count', 'verbose_name_plural': 'View Counts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Subject Entry', 'verbose_name_plural': 'Subject Entry'},
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
